#! /bin/bash
  
# we are in $BPMS/test
export HERE=`dirname "$0"`
cd $HERE/..

export BPMS=`pwd`
name=`basename "$0"`


# for testing
libb=$BPMS/src
bin=$BPMS/src
verbose=0

for i in "$@"
do
case $i in
    -p|-q|--quite)
    verbose=0
    shift # past argument with no value
    ;;
    -v|--verbose)
    verbose=1
    shift # past argument with no value
    ;;
    -i|--install_test)
    libb=$BPMS/lib
    bin=$BPMS/bin
    shift # past argument with no value
    ;;
    -t|--test)
    libb=$BPMS/src
    bin=$BPMS/src
    shift # past argument with no value
    ;;
    *)
    echo "Error: Unknown option $i in $name (from $HERE) args $*" >&2
    echo "  Options: $name [-v|--verbose] [-p|-q|-quiet] [-i|--install_test] [-t|--test]" >&2
    exit 1
          # unknown option
    ;;
esac
done

export LD_LIBRARY_PATH="${libb}:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="${libb}:$DYLD_LIBRARY_PATH"

export TEST=$BPMS/test/${name}_files
#export MATLIB=$TEST
#export MATERIAL=$TEST
#export RSRLIB=$TEST
#export SKY_ILLUMINATION=$TEST
#export ARARAT_OBJECT=$TEST
#export DIRECT_ILLUMINATION=$TEST
export BPMS_FILES=$TEST


if [ $verbose == 1 ]
then
  echo "==========="
  env
  echo "==========="
  "${bin}"/start < $TEST/starttest.ip -sensor_wavebands wavebands.dat -m 100 -sun_position 0 0 10 test.obj 1> $TEST/$name.op

  s=$?
  echo "start exit code: $s"
  echo "template:"
  echo "==========="
  cat $TEST/$name.test.op

  echo "this:"
  echo "============="
  cat $TEST/$name.op
  echo "sucess $s"
else
  "${bin}"/start < $TEST/starttest.ip -sensor_wavebands wavebands.dat -m 100 -sun_position 0 0 10 test.obj 1> $TEST/$name.op
  s=$?
fi

if [ $s == 1 ]
then
  echo "error running " "${bin}/start < $TEST/starttest.ip -sensor_wavebands wavebands.dat -m 100 -sun_position 0 0 10 test.obj 1> $TEST/$name.op"
fi

diff $TEST/$name.test.op $TEST/$name.op >/dev/null
s=$?

exit $s
