#define	FILE_END	9

#define	UNKNOWN_TYPE	0
#define	OPEN_BBOX_RET	100
#define	OPEN_BBOX	"!{"
#define	CLOSE_BBOX_RET	1
#define	CLOSE_BBOX	"!}"
#define	GROUP_RET	2
#define	GROUP		"g"
#define	VERTEX_RET	3
#define	VERTEX		"v"
#define	LOCAL_RET	4
#define	LOCAL		"!local"
#define	NORMAL_RET	5
#define	NORMAL1		"!n"
#define	NORMAL2		"!normal"
#define	DEFINE_RET	6
#define	DEFINE1		"!define"
#define	DEFINE2		"#define"
#define	TRIANGLE_RET	7
#define	TRIANGLE1	"f"
#define	TRIANGLE2	"fo"
#define	SPHERE_RET	8
#define	SPH		"sph"
#define	ELLIPSE_RET	17
#define	ELL		"ell"
#define SPHER_RET    26
#define SPHER             "spheroid"
#define	CYLINDER_RET	9
#define	CYL		"cyl"
#define	CLONE_RET	10
#define	CLONE1		"clone"
#define	CLONE2		"!clone"
#define	CLONE3		"#clone"
#define	DEM_RET		11
#define	DEM1		"DEM"
#define	DEM2		"!DEM"
#define	DEM3		"#DEM"
#define	DEM4		"dem"
#define	DEM5		"!dem"
#define	DEM6		"#dem"
#define	PLANE_RET	12
#define	PLANE1		"PLANE"
#define	PLANE2		"!PLANE"
#define	PLANE3		"#PLANE"
#define	PLANE4		"plane"
#define	PLANE5		"!plane"
#define	PLANE6		"#plane"
#define	USEMTL_RET	13
#define	USEMTL		"usemtl"
#define	MTLLIB_RET	14
#define	MTLLIB		"mtllib"
#define	TRANS_RET	15
/*#define	TRANS		"transformation"
*/
#define       TRANS            "transformation_matrix"
#define	SPHERICAL_DEM_RET		16
#define	SPHERICAL_DEM1		"SPHERICAL_DEM"
#define	SPHERICAL_DEM2		"!SPHERICAL_DEM"
#define	SPHERICAL_DEM3		"#SPHERICAL_DEM"
#define	SPHERICAL_DEM4		"spherical_dem"
#define	SPHERICAL_DEM5		"!spherical_dem"
#define	SPHERICAL_DEM6		"#spherical_dem"
#define	VOLUME_SPHERE_RET	18
#define	VOLUME_SP		"vsph"
#define	CLOSED_CYL	"ccyl"
#define	CLOSED_CYL_RET	19
#define	VOLUME_CYL_RET	20
#define	VOLUME_CYL	"vcyl"
#define	DISK_RET	21
#define	DISK1	"disc"
#define	DISK2	"disk"
#define	BILINEARPATCH_RET	23
#define	BILINEARPATCH0	"blp"
#define	BILINEARPATCH1	"#blp"
#define	BILINEARPATCH2	"!blp"
#define	BILINEARPATCH3	"BiLinearPatch"
#define	BILINEARPATCH4	"biLinearPatch"
#define	BILINEARPATCH5	"!BiLinearPatch"
#define	BILINEARPATCH6	"!biLinearPatch"
#define	BILINEARPATCH7	"#BiLinearPatch"
#define	BILINEARPATCH8	"#biLinearPatch"
#define	VOLUME_ELLIPSE_RET	22
#define	VOLUME_ELLIPSE	"vell"
#define VOLUME_SPHEROID_RET      25
#define VOLUME_SPHEROID  "vspheroid"



